sudo: false
language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r requirements_for_test.txt
script:
- ./scripts/run_tests.sh
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: sPJW6vWpLv6OQsH9WBySuuGu7ltSkq5VeI36VKmhWrW1dDZiw19hkya4jW0rwZfZkcUYY+K8H5tqpgEcyc1/12fEeKgFJuj+9+vPeywYGT1PjQo//fu+HbEpBVY8Ubdpt07N2JbBa3Z3/DvhrqcHGw/sk2JshIfOqKkCbrelL81n691YZO5BZXsnKGqzPFlSXFqE4fpvq0/e/xyOcIUbiWgGhgIbw8AQSuPx24PmZ7+u6SUAFs4V61X6idYNENP3Zvgfg00DI006QhEBJdZTHu63QQsoEU+elBFuPsbPZBwzlyshsUZjJedF68PtcBnkdqIN907SPZhXBmRvw4X3k4uA3KwMi2K7JgM+qCRtD+vt3WuBMNHKwbZPdKHe0Mul71GvNK7XOzk8Fa3/j2YrghGL6dYQ+JYpeXGo14aUQ8wWQf4Dn/eIt/AZbIEblHC5TZ0VESITkVf6CTSTPoynO1x0PDSIS1X8njUVikKOOO4mY3QAGkvHigHxUs/L4J8PxWeL5djGYB88e1EmCNmunSo9QWcwUeXaS3+r4UDoK54mU3ZQ09dIYsxycjWRKQRe+DdK2wlwhWSAC2H5zhFdWgKVyCOXskNDM13qE3ppM/sJlv1TqjjagcQQVl47zkEnRknCy+LZW0dJi682pg8W0bJjwMbBoy0upndbc/0ScBw=
