sudo: false
language: python
python:
- '3.4'
addons:
  postgresql: "9.3"
env:
  - SQLALCHEMY_DATABASE_URI=postgresql://postgres:@localhost:5432/notify_test
install:
  - pip install -r requirements_for_test.txt
before_script:
  - psql -c 'create database notify_test;' -U postgres
script:
  - ./scripts/run_tests.sh
notifications:
  email: false
  slack:
    secure: MFUBET2AoQhlbNaZvzthL8G3FaP/TXcevvjdE00s9vl2CFoxGN5s/D5lIuNJ7cbUEk0nvoYPNNN1XbdI7Y9GI/wsZLT7H/Ss1tilEtbhXurDM8knZxb5MMCmCjCVF4KvVSF2oosEEXdJoKYBEeJoRd6zPnnJT4ZuXVeuGZUY73hae0JloP/+ZFbb+OD5HozL0wPk3fDOhtD73GsDJxYMCUbadeaRr5l5k5y18BnELiFPeubZZc2z+TC8prFIMShOdJdUs+bpmsZc89J34BAkyDe7fEJ+oxU7sqpvTmea/pczDaWOxuwcqGdyC9mO8iV26x8LSyLum3nDJt9MDTipvcvpI8yBAopKw+JlBYS/54tZAmlRIUQkM6V4+1SDFqdt5EZyVdqgr7wokqCwMkC7pNFsdkAHzdrRcMwy8QbpVLhAPdWShoWYI4bG6ZMoZkLEzVUjeseTDcEDbH09HZP8+g1OWRqXNPfGHMhCT/Yb2xM6CgrsrVx7AAH1B33lHQYu5+vwMQpRw6/sgtnf/UBU4Y0BhpkjLVDQsf9BedcXm+iugmJz32mpTClbz1ze/PtU+2TuzI56zMD5EMyWTQ4cYZ1HNpnT8XXm3NumRU8WgfN1nxtu2ru203atFCEDWba2n5DXrrkNJlkpNxmIeYz37v/MoQvvuiedFitjBfKYMxU=
deploy:
  provider: heroku
  api_key:
    secure: sPJW6vWpLv6OQsH9WBySuuGu7ltSkq5VeI36VKmhWrW1dDZiw19hkya4jW0rwZfZkcUYY+K8H5tqpgEcyc1/12fEeKgFJuj+9+vPeywYGT1PjQo//fu+HbEpBVY8Ubdpt07N2JbBa3Z3/DvhrqcHGw/sk2JshIfOqKkCbrelL81n691YZO5BZXsnKGqzPFlSXFqE4fpvq0/e/xyOcIUbiWgGhgIbw8AQSuPx24PmZ7+u6SUAFs4V61X6idYNENP3Zvgfg00DI006QhEBJdZTHu63QQsoEU+elBFuPsbPZBwzlyshsUZjJedF68PtcBnkdqIN907SPZhXBmRvw4X3k4uA3KwMi2K7JgM+qCRtD+vt3WuBMNHKwbZPdKHe0Mul71GvNK7XOzk8Fa3/j2YrghGL6dYQ+JYpeXGo14aUQ8wWQf4Dn/eIt/AZbIEblHC5TZ0VESITkVf6CTSTPoynO1x0PDSIS1X8njUVikKOOO4mY3QAGkvHigHxUs/L4J8PxWeL5djGYB88e1EmCNmunSo9QWcwUeXaS3+r4UDoK54mU3ZQ09dIYsxycjWRKQRe+DdK2wlwhWSAC2H5zhFdWgKVyCOXskNDM13qE3ppM/sJlv1TqjjagcQQVl47zkEnRknCy+LZW0dJi682pg8W0bJjwMbBoy0upndbc/0ScBw=
  app:
    master: test-notify-api
