sudo: false
language: python
python:
- '3.4'
addons:
  postgresql: '9.3'
env:
- SQLALCHEMY_DATABASE_URI=postgresql://postgres:@localhost:5432/notify_test
install:
- pip install -r requirements_for_test.txt
before_script:
- psql -c 'create database notify_test;' -U postgres
script:
- ./scripts/run_tests.sh
deploy:
  provider: heroku
  api_key:
    secure: sPJW6vWpLv6OQsH9WBySuuGu7ltSkq5VeI36VKmhWrW1dDZiw19hkya4jW0rwZfZkcUYY+K8H5tqpgEcyc1/12fEeKgFJuj+9+vPeywYGT1PjQo//fu+HbEpBVY8Ubdpt07N2JbBa3Z3/DvhrqcHGw/sk2JshIfOqKkCbrelL81n691YZO5BZXsnKGqzPFlSXFqE4fpvq0/e/xyOcIUbiWgGhgIbw8AQSuPx24PmZ7+u6SUAFs4V61X6idYNENP3Zvgfg00DI006QhEBJdZTHu63QQsoEU+elBFuPsbPZBwzlyshsUZjJedF68PtcBnkdqIN907SPZhXBmRvw4X3k4uA3KwMi2K7JgM+qCRtD+vt3WuBMNHKwbZPdKHe0Mul71GvNK7XOzk8Fa3/j2YrghGL6dYQ+JYpeXGo14aUQ8wWQf4Dn/eIt/AZbIEblHC5TZ0VESITkVf6CTSTPoynO1x0PDSIS1X8njUVikKOOO4mY3QAGkvHigHxUs/L4J8PxWeL5djGYB88e1EmCNmunSo9QWcwUeXaS3+r4UDoK54mU3ZQ09dIYsxycjWRKQRe+DdK2wlwhWSAC2H5zhFdWgKVyCOXskNDM13qE3ppM/sJlv1TqjjagcQQVl47zkEnRknCy+LZW0dJi682pg8W0bJjwMbBoy0upndbc/0ScBw=
  app:
    master: test-notify-api
  run:
  - python application.py db upgrade
notifications:
  slack:
    rooms:
      secure: MMDS75tBOitrK4FXShmUjRB687GtCnVKvq0640Q4pWXaqBVVojQ2p9GlYYpFHxTmG7DhvPBjlq6MaTH41mwJwjO3y7cH2iWL69KbFX2PvjOk+zwIzdzIi29uhs9aOhhILvomT0HY2PPjLnHkrcrBszYG7LYvac+eqnzAdOlzSAozazfAGI1IUF3UdcZX4awLgv027WnxC2CXm/ZY7l1xsLwxtACKIC0CS2fB0fgK7BJfFOKTjvj60gKx15ffR2gRVMNklYaW2VuaATT/VMeLJjYVoWeHkOIqW5yqKBelWQfWXIivmDfhL0zPk69sm51w3sQkzJxsr67rzjdpUx8WqFtin/CCIHwDJluOmIRD8rWZSgQf5LQUPy+gsUvSyoeebuh/hA7I8x7hYvmiptCVDi8mBjVFxfSSODQscJii61QDraOCrJYqWWabHPY4TeqHw7HqAgHBidHquowsZWuxyfhCMaRQLS72HTWKWNkK44+y8v1E+TomYmTvFg4ZSLFkievmhxsR5FUewbXjQ64zKw3oBT56H2queCLJ7MiLZNvza239T4/lqPIcF7YrOhrce3ozONviWtoYldq9NNPQSkObw0NdTi7PkY4xF2Nw6MaDWuIAhmkRIJNC3JdadkJ8ZdzztRdYhUjp/6L42oLaOcsJdE99URUhtj9GWaLGyK0=
