"""empty message

Revision ID: 100_remove_org_from_service
Revises: 90_remove_org_from_user
Create Date: 2015-10-23 16:36:17.355276

"""

# revision identifiers, used by Alembic.
revision = '100_remove_org_from_service'
down_revision = '90_remove_org_from_user'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('services_organisations_id_fkey', 'services', type_='foreignkey')
    op.drop_column('services', 'organisations_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('organisations_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('services_organisations_id_fkey', 'services', 'organisations', ['organisations_id'], ['id'])
    ### end Alembic commands ###
