"""empty message

Revision ID: 10_create_organisations
Revises: None
Create Date: 2015-10-08 15:28:40.207251

"""

# revision identifiers, used by Alembic.
revision = '10_create_organisations'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation')
    ### end Alembic commands ###
