"""empty message

Revision ID: 110_add_restricted_to_service
Revises: 100_remove_org_from_service
Create Date: 2015-10-26 11:16:20.101868

"""

# revision identifiers, used by Alembic.
revision = '110_add_restricted_to_service'
down_revision = '100_remove_org_from_service'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('restricted', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'restricted')
    ### end Alembic commands ###
