"""empty message

Revision ID: 130_add_sender_name
Revises: 120_usage_table
Create Date: 2015-10-30 10:25:48.785953

"""

# revision identifiers, used by Alembic.
revision = '130_add_sender_name'
down_revision = '120_usage_table'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sender', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_notifications_sender'), 'notifications', ['sender'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_sender'), table_name='notifications')
    op.drop_column('notifications', 'sender')
    ### end Alembic commands ###
