"""empty message

Revision ID: 140_add_desc_to_notification
Revises: 130_add_sender_name
Create Date: 2015-10-30 14:58:41.262911

"""

# revision identifiers, used by Alembic.
revision = '140_add_desc_to_notification'
down_revision = '130_add_sender_name'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'description')
    ### end Alembic commands ###
