"""empty message

Revision ID: 1e8f1f2b22
Revises: 180_not_null_token_type
Create Date: 2015-11-04 11:23:29.305631

"""

# revision identifiers, used by Alembic.
revision = '1e8f1f2b22'
down_revision = '180_not_null_token_type'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_mobile_number_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_mobile_number_key', 'users', ['mobile_number'])
    ### end Alembic commands ###
