"""empty message

Revision ID: 20_create_service
Revises: 10_create_organisations
Create Date: 2015-10-08 15:43:28.765668

"""

# revision identifiers, used by Alembic.
revision = '20_create_service'
down_revision = '10_create_organisations'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    ### end Alembic commands ###
