"""empty message

Revision ID: 20_update_users
Revises: 10_bootstrap
Create Date: 2015-10-14 12:00:27.626291

"""

# revision identifiers, used by Alembic.
revision = '20_update_users'
down_revision = '10_bootstrap'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('logged_in_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logged_in_at')
    op.drop_column('users', 'failed_login_count')
    ### end Alembic commands ###
