"""empty message

Revision ID: 30_remove_locked_column
Revises: 20_update_users
Create Date: 2015-10-14 12:10:04.163884

"""

# revision identifiers, used by Alembic.
revision = '30_remove_locked_column'
down_revision = '20_update_users'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
