"""empty message

Revision ID: 40_sent_at_column
Revises: 30_remove_locked_column
Create Date: 2015-10-19 13:06:22.579436

"""

# revision identifiers, used by Alembic.
revision = '40_sent_at_column'
down_revision = '30_remove_locked_column'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'sent_at')
    ### end Alembic commands ###
