"""empty message

Revision ID: 50_add_created_at_dates
Revises: 40_create_message
Create Date: 2015-10-08 15:49:38.717412

"""

# revision identifiers, used by Alembic.
revision = '50_add_created_at_dates'
down_revision = '40_create_message'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('service', sa.Column('created_at', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'created_at')
    op.drop_column('job', 'created_at')
    ### end Alembic commands ###
