"""empty message

Revision ID: 60_add_delivered_at_date
Revises: 50_add_created_at_dates
Create Date: 2015-10-08 16:01:38.874067

"""

# revision identifiers, used by Alembic.
revision = '60_add_delivered_at_date'
down_revision = '50_add_created_at_dates'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'delivered_at')
    ### end Alembic commands ###
