"""empty message

Revision ID: 70_user_service_join_table
Revises: 60_add_active_and_limit
Create Date: 2015-10-20 12:52:05.661965

"""

# revision identifiers, used by Alembic.
revision = '70_user_service_join_table'
down_revision = '60_add_active_and_limit'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_service',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_service')
    ### end Alembic commands ###
