"""empty message

Revision ID: 80_adding_token_and_indexes
Revises: 70_create_user_table
Create Date: 2015-10-09 13:12:32.370312

"""

# revision identifiers, used by Alembic.
revision = '80_adding_token_and_indexes'
down_revision = '70_create_user_table'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_service_id'), 'job', ['service_id'], unique=False)
    op.create_index(op.f('ix_notification_job_id'), 'notification', ['job_id'], unique=False)
    op.add_column('service', sa.Column('token', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_service_organisation_id'), 'service', ['organisation_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_organisation_id'), table_name='service')
    op.drop_column('service', 'token')
    op.drop_index(op.f('ix_notification_job_id'), table_name='notification')
    op.drop_index(op.f('ix_job_service_id'), table_name='job')
    ### end Alembic commands ###
