"""empty message

Revision ID: 80_add_mobile_to_user
Revises: 70_user_service_join_table
Create Date: 2015-10-23 14:39:41.563079

"""

# revision identifiers, used by Alembic.
revision = '80_add_mobile_to_user'
down_revision = '70_user_service_join_table'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['mobile_number'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'mobile_number')
    ### end Alembic commands ###
