"""empty message

Revision ID: 13bd0a689f4_
Revises: 80_add_mobile_to_user
Create Date: 2015-10-23 15:25:31.559522

"""

# revision identifiers, used by Alembic.
revision = '13bd0a689f4_'
down_revision = '80_add_mobile_to_user'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_organisation_id', table_name='users')
    op.drop_constraint('users_organisation_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'organisation_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_organisation_id_fkey', 'users', 'organisations', ['organisation_id'], ['id'])
    op.create_index('ix_users_organisation_id', 'users', ['organisation_id'], unique=False)
    ### end Alembic commands ###
